server:
  error:
    include-stacktrace: on_param

spring:
  datasource:
#    url: jdbc:postgresql://localhost/avaliacao?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    url: jdbc:mysql://localhost:6603/avaliacao
    username: root
    password: faat
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect