server:
  error:
    include-stacktrace: on_param

spring:
  datasource:
    url: jdbc:postgresql://localhost/avaliacao?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
#    url: jdbc:mysql://localhost:6603/avaliacao
    username: osmar
    password: 123mudar
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect